# Generated by Django 5.2.15 on 2026-06-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loyverse_customer_id', models.CharField(help_text='Loyverse Native Customer ID', max_length=255, unique=True)),
                ('phone_number', models.CharField(help_text='E.164 formatted number used as unique login ID', max_length=20, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField(help_text='Required for age +18 compliance and Birthday automated marketing campaigns')),
                ('is_verified', models.BooleanField(default=False, help_text='True only after successful WhatsApp OTP validation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password_hash', models.CharField(help_text='Argon2 or BCrypt hash', max_length=255)),
                ('employee_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('ADMIN', 'Owner/Manager'), ('WAITER', 'Floor Staff')], default='WAITER', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
