# Generated by Django 5.2.15 on 2026-06-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='+962 79 123 4567', max_length=50)),
                ('whatsapp_number', models.CharField(default='962791234567', help_text='WhatsApp format without + or spaces, e.g. 962791234567', max_length=50)),
                ('email', models.EmailField(default='info@26cafe.com', max_length=254)),
                ('location_desc_en', models.CharField(default='Wadi Musa, Petra Road - Near Petra Visitor Center', max_length=255)),
                ('location_desc_ar', models.CharField(default='وادي موسى، شارع البتراء - بالقرب من مركز زوار البتراء', max_length=255)),
                ('latitude', models.FloatField(default=30.3222)),
                ('longitude', models.FloatField(default=35.4795)),
                ('opening_hours_en', models.CharField(default='Daily: 7:30 AM - 11:30 PM', max_length=255)),
                ('opening_hours_ar', models.CharField(default='يومياً: 7:30 صباحاً - 11:30 مساءً', max_length=255)),
            ],
            options={
                'verbose_name': 'Cafe Configuration',
                'verbose_name_plural': 'Cafe Configuration',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(help_text='Email or Phone number', max_length=255)),
                ('inquiry_type', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
    ]
