# Generated by Django 5.2.15 on 2026-06-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cafeconfiguration_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeconfiguration',
            name='facebook_url',
            field=models.URLField(blank=True, default='https://facebook.com/26cafe', null=True),
        ),
        migrations.AddField(
            model_name='cafeconfiguration',
            name='instagram_url',
            field=models.URLField(blank=True, default='https://instagram.com/26cafe', null=True),
        ),
        migrations.AddField(
            model_name='cafeconfiguration',
            name='tiktok_url',
            field=models.URLField(blank=True, default='https://tiktok.com/@26cafe', null=True),
        ),
    ]
