# Generated by Django 5.2.15 on 2026-06-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_cafeconfiguration_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeconfiguration',
            name='ultramsg_instance_id',
            field=models.CharField(blank=True, help_text='UltraMsg Instance ID (e.g. instance12345)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cafeconfiguration',
            name='ultramsg_token',
            field=models.CharField(blank=True, help_text='UltraMsg API Token', max_length=100, null=True),
        ),
    ]
