# Generated by Django 5.2.15 on 2026-06-28 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_cafeconfiguration_ultramsg_instance_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeconfiguration',
            name='birthday_msg_bronze',
            field=models.TextField(default='Happy Birthday! Enjoy 15% off today.'),
        ),
        migrations.AddField(
            model_name='cafeconfiguration',
            name='birthday_msg_gold',
            field=models.TextField(default='Happy Birthday! Enjoy a free drink + dessert today.'),
        ),
        migrations.AddField(
            model_name='cafeconfiguration',
            name='birthday_msg_silver',
            field=models.TextField(default='Happy Birthday! Enjoy a free drink today.'),
        ),
        migrations.AddField(
            model_name='cafeconfiguration',
            name='gold_tier_threshold',
            field=models.FloatField(default=50.0, help_text='Monthly spend in JOD for Gold Tier'),
        ),
        migrations.AddField(
            model_name='cafeconfiguration',
            name='points_conversion_rate',
            field=models.FloatField(default=100.0, help_text='Points per 1 JOD discount value'),
        ),
        migrations.AddField(
            model_name='cafeconfiguration',
            name='promo_video_desktop',
            field=models.URLField(blank=True, help_text='Desktop Cinematic Video Embed URL', null=True),
        ),
        migrations.AddField(
            model_name='cafeconfiguration',
            name='promo_video_mobile',
            field=models.URLField(blank=True, help_text='Mobile Vertical Video Embed URL', null=True),
        ),
        migrations.AddField(
            model_name='cafeconfiguration',
            name='raffle_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cafeconfiguration',
            name='raffle_prize_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cafeconfiguration',
            name='raffle_prize_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cafeconfiguration',
            name='raffle_prize_name',
            field=models.CharField(default='Premium Coffee Box', max_length=255),
        ),
        migrations.AddField(
            model_name='cafeconfiguration',
            name='raffle_ticket_threshold',
            field=models.FloatField(default=5.0, help_text='Minimum JOD spent per raffle ticket'),
        ),
        migrations.AddField(
            model_name='cafeconfiguration',
            name='silver_tier_threshold',
            field=models.FloatField(default=20.0, help_text='Monthly spend in JOD for Silver Tier'),
        ),
        migrations.CreateModel(
            name='CustomerVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_code', models.CharField(max_length=50, unique=True)),
                ('voucher_type', models.CharField(help_text='GIFT or BIRTHDAY', max_length=20)),
                ('reward_details', models.CharField(max_length=255)),
                ('is_redeemed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='accounts.customerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RaffleTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(max_length=50, unique=True)),
                ('receipt_number', models.CharField(max_length=100)),
                ('receipt_amount', models.FloatField()),
                ('draw_status', models.CharField(default='PENDING', help_text='PENDING, WON, or LOST', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffle_tickets', to='accounts.customerprofile')),
            ],
        ),
    ]
