# Generated by Django 5.2.15 on 2026-06-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_cafeconfiguration_birthday_msg_bronze_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='monthly_spend',
            field=models.FloatField(default=0.0, help_text='Calculated monthly spend for tier status'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='points_balance',
            field=models.IntegerField(default=0, help_text='Synced Loyverse points balance'),
        ),
    ]
