# Generated by Django 5.2.15 on 2026-06-28 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customerprofile_monthly_spend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeconfiguration',
            name='featured_item_desc',
            field=models.TextField(blank=True, default='جرب صنفنا الجديد المميز بنكهة الزعفران الفاخرة الممزوجة مع الإسبريسو العضوي.', null=True),
        ),
        migrations.AddField(
            model_name='cafeconfiguration',
            name='featured_item_is_active',
            field=models.BooleanField(default=False, help_text='Toggle to display a special featured item launch card on the menu'),
        ),
        migrations.AddField(
            model_name='cafeconfiguration',
            name='featured_item_name',
            field=models.CharField(blank=True, default='Saffron Latte / لاتيه الزعفران', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cafeconfiguration',
            name='featured_item_special_price',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Discounted price for trying the new item', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cafeconfiguration',
            name='featured_item_video',
            field=models.URLField(blank=True, help_text='Promo video link for the new item (YouTube or MP4)', null=True),
        ),
    ]
