# Generated by Django 5.2.15 on 2026-08-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_cafeconfiguration_featured_item_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeconfiguration',
            name='cafe_name',
            field=models.CharField(default='White Bird Cafe', help_text='The name of the cafe displayed on the website', max_length=255),
        ),
    ]
