# Generated by Django 5.2.15 on 2026-08-26 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_cafeconfiguration_cafe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeconfiguration',
            name='featured_item_video',
            field=models.FileField(blank=True, help_text='Promo video file for the new item', null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='cafeconfiguration',
            name='promo_video_desktop',
            field=models.FileField(blank=True, help_text='Desktop Cinematic Video File', null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='cafeconfiguration',
            name='promo_video_mobile',
            field=models.FileField(blank=True, help_text='Mobile Vertical Video File', null=True, upload_to='videos/'),
        ),
    ]
