# Generated by Django 5.2.15 on 2026-08-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_cafeconfiguration_featured_item_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeconfiguration',
            name='raffle_prize_image',
            field=models.FileField(blank=True, help_text='Raffle Prize Image File', null=True, upload_to='prizes/'),
        ),
    ]
