# Generated by Django 5.2.15 on 2026-08-26 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_cafeconfiguration_raffle_prize_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='barcode',
            field=models.CharField(blank=True, help_text='Loyverse customer barcode for scanning', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cafeconfiguration',
            name='gold_tier_threshold',
            field=models.FloatField(default=1500.0, help_text='Total points earned in last 12 months for Gold Tier'),
        ),
        migrations.AlterField(
            model_name='cafeconfiguration',
            name='silver_tier_threshold',
            field=models.FloatField(default=500.0, help_text='Total points earned in last 12 months for Silver Tier'),
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(help_text='Points earned (positive) or redeemed (negative)')),
                ('transaction_type', models.CharField(default='EARNED', help_text='EARNED, REDEEMED, or BIRTHDAY', max_length=20)),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to='accounts.customerprofile')),
            ],
        ),
    ]
