# Generated by Django 5.2.15 on 2026-08-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customerprofile_barcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Loyverse customer barcode for scanning', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
