# Generated by Django 5.2.15 on 2026-08-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customerprofile_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeconfiguration',
            name='map_image',
            field=models.FileField(blank=True, help_text='صورة ثابتة لخريطة موقع الكافيه (Screenshot)', null=True, upload_to='maps/'),
        ),
    ]
