# Generated by Django 5.2.15 on 2026-08-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_staffpushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeconfiguration',
            name='loyverse_api_token',
            field=models.CharField(blank=True, help_text='Loyverse POS Access Token', max_length=255, null=True),
        ),
    ]
