# Generated by Django 5.2.15 on 2026-08-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_cafeconfiguration_loyverse_api_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeconfiguration',
            name='hero_subtitle_ar',
            field=models.CharField(default='تجربة استثنائية من القهوة المختصة والمشروبات الساخنة والباردة', help_text='الوصف الترويجي الافتتاحي', max_length=255),
        ),
        migrations.AddField(
            model_name='cafeconfiguration',
            name='hero_subtitle_en',
            field=models.CharField(default='An exceptional specialty coffee & drinks experience', help_text='Hero Subtitle', max_length=255),
        ),
        migrations.AddField(
            model_name='cafeconfiguration',
            name='hero_title_ar',
            field=models.CharField(default='وايت بيرد كافيه', help_text='العنوان الرئيسي في الصفحة الرئيسية', max_length=255),
        ),
        migrations.AddField(
            model_name='cafeconfiguration',
            name='hero_title_en',
            field=models.CharField(default='White Bird Cafe', help_text='Main Hero Title', max_length=255),
        ),
        migrations.AddField(
            model_name='cafeconfiguration',
            name='menu_cover_image',
            field=models.FileField(blank=True, help_text='صورة غلاف بوابة المنيو', null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='cafeconfiguration',
            name='wifi_password',
            field=models.CharField(blank=True, default='whitebird2026', help_text='كلمة سر واي فاي الكافيه', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cafeconfiguration',
            name='wifi_ssid',
            field=models.CharField(blank=True, default='WhiteBird_Guest', help_text='اسم شبكة واي فاي الكافيه للزوار', max_length=100, null=True),
        ),
    ]
