# Generated by Django 5.2.15 on 2026-06-12 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loyverse_category_id', models.CharField(help_text='Direct link to Loyverse Category ID', max_length=255, unique=True)),
                ('pos_category_name', models.CharField(help_text='Original practical name in Loyverse POS', max_length=255)),
                ('display_category_name', models.CharField(help_text='Premium marketing name displayed on web', max_length=255)),
                ('category_image', models.URLField(blank=True, null=True)),
                ('order_index', models.IntegerField(default=0, help_text='Custom presentation ordering')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loyverse_id', models.CharField(help_text='Loyverse Item ID', max_length=255, unique=True)),
                ('pos_name', models.CharField(help_text='Original short name in POS', max_length=255)),
                ('display_name', models.CharField(help_text='Premium display name for customers', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Marketing food/drink description', null=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('image', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Force Available (Ignore Negative Stock)'), ('OUT_OF_STOCK', 'Force Hidden / Temporary Out of Stock'), ('AUTOMATIC', 'Follow Loyverse Live Stock tracking')], default='AVAILABLE', max_length=20)),
                ('order_index', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menucategory')),
            ],
        ),
    ]
