# Generated by Django 5.2.15 on 2026-06-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menusection_menutab_menuitem_is_caffeine_free_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menutab',
            name='image',
            field=models.URLField(blank=True, help_text='Image URL for this tab that changes when selected', null=True),
        ),
    ]
