# Generated by Django 5.2.15 on 2026-08-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menutab_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='show_fresh_badge',
            field=models.BooleanField(default=False, help_text="إظهار وسم 'متوفر طازجاً'"),
        ),
    ]
